import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {fileURLToPath} from 'node:url';
test('route saves persist, conflicts are rejected, and foreign origins cannot write',async()=>{
  const data=await fs.mkdtemp(path.join(os.tmpdir(),'bigwalk-companion-test-'));
  const root=fileURLToPath(new URL('..',import.meta.url));
  const telemetry=path.join(data,'manager profile','BepInEx','companion');
  await fs.mkdir(telemetry,{recursive:true});
  const sample={timestamp:Date.now(),players:[{id:'fixture',x:1,y:2,z:3}]};
  await fs.writeFile(path.join(telemetry,'positions.json'),JSON.stringify(sample));
  await fs.writeFile(path.join(telemetry,'session-abc123.jsonl'),JSON.stringify(sample)+'\n');
  await fs.writeFile(path.join(telemetry,'map.png'),'fixture-map');
  const child=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'4318',COMPANION_DATA_DIR:data,BIGWALK_PATH:path.join(data,'unused-game'),COMPANION_TELEMETRY_DIR:telemetry},stdio:['ignore','pipe','pipe']});
  try{
    await Promise.race([once(child.stdout,'data'),once(child,'exit').then(()=>{throw new Error('Test server exited early');}),new Promise((_,reject)=>{const timer=setTimeout(()=>reject(new Error('Startup timed out')),10000);timer.unref();})]);
    const base='http://127.0.0.1:4318';
    assert.deepEqual((await(await fetch(base+'/api/live')).json()).frame,sample);
    assert.equal((await(await fetch(base+'/api/recordings')).json())[0].id,'session-abc123.jsonl');
    assert.deepEqual(await(await fetch(base+'/api/recording?id=session-abc123.jsonl')).json(),[sample]);
    assert.equal((await(await fetch(base+'/api/map-status')).json()).available,true);
    const state=await(await fetch(base+'/api/state')).json();
    state.pack.areas.push({id:'fixture',name:'Test area',notes:'Line 1\nLine 2',x:.2,y:.2,w:.1,h:.1});
    state.pack.pois.push({id:'poi',icon:'train-front',name:'Station',notes:'Meet here',category:'transport',color:'#c5f785',u:.3,v:.4});
    state.pack.routes.push({id:'route',name:'Sprint',notes:'Two players',color:'#ffd458',points:[{u:.1,v:.2},{u:.3,v:.4}],steps:[{id:'step',name:'Meet up',notes:'Both runners',poiId:'poi'}]});
    const options={method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)};
    assert.equal((await fetch(base+'/api/state',options)).status,200);
    assert.equal((await fetch(base+'/api/state',options)).status,409);
    assert.equal((await fetch(base+'/api/state',{...options,headers:{...options.headers,Origin:'https://example.com'}})).status,403);
    assert.equal((await fetch(base+'/api/recording?id=../../README.md')).status,404);
    const saved=JSON.parse(await fs.readFile(path.join(data,'route-pack.json'),'utf8'));
    assert.equal(saved.pack.areas[0].notes,'Line 1\nLine 2');
    assert.equal(saved.revision,1);
    assert.deepEqual(saved.pack.pois,state.pack.pois);assert.deepEqual(saved.pack.routes,state.pack.routes);
    assert.equal((await fetch(base+'/planner.mjs')).status,200);
    assert.equal((await fetch(base+'/planning-data.mjs')).status,200);
    const updated=await fetch(base+'/api/state',{...options,body:JSON.stringify({...saved,pack:{...saved.pack,name:'Changed'}})});
    assert.equal(updated.status,200);
    assert.deepEqual(JSON.parse(await fs.readFile(path.join(data,'route-pack.previous.json'),'utf8')),saved);
    const invalid={...saved,pack:{...saved.pack,calibration:[{x:0,z:0,u:2,v:0}]}};
    assert.equal((await fetch(base+'/api/state',{...options,body:JSON.stringify(invalid)})).status,400);
  }finally{const exited=once(child,'exit');child.kill();await exited;}
});
